sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
- '5'
- '4'
env:
  global:
  - secure: L/ln4ITdV42SmmOcm6/mad7sFpRD7RtbBxdCpe7jUbWL9m5Qp27R6sAGBTt2OQDo3K3yGfa+dbsfS7qWB2/TPRgB4xZEWCAS5UjYq6q+afW4DhYo3kJ0WO3mzZV27KXBO3O300cw/8+7oo+sdupcJCvEvPHWXbDn4gUZEI4TTbsv9SrLft0eAl9W0CecTTDbA1w2WQ14gucaentxpFhTcmofQK26/4S9nMLp5a3g+kJv3j2T0D3pnmAvLD9GkUihQL2L3xrbknjrJj2SSn/X/efKPxlH5MowvMtY7Vq1CBwWhW6ZNtRFTMOxfUGu0K5OcEUflNAmfpPFjpG/wpIl79DjkiscklsAy4mgUAf57vCh83Y33jfz/p3KsJjh5s7LlA+rqbSqPipTmllvZSAz6PSPtIqKQGBKpIJS2tngQ9LFNKvQRVsdrMupdKpWxaoNALDi7u78piNHUraCJ33gmEpBK1DUnjE0IX8BwT7nHrhcnf7zRcj06NITVnrW4y6SrQGKBNESONliWXe2TwKuzMqM++9xBGUwXRM1PM/2jkn36Y9xc6b85OuRO77eZbEdf03bRLnAPLqt9pVMjDTy0e85Q1kPrzHoY6IFgnTPSpiU2zLEBYsxTvufmDcVIsMemDk0G69E8WV/vS3nc7sd4mfNLsId3ZakPFl+29JAfOc=
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  api_key:
    secure: m3/Wev2JYcVtwJFAhcxhjInO2i20+uT80xethKuhxt0AeqnaEVQy3sIRU+uXsD36Yogl3BiZMCwkMKZF44IzW78o11NpXqIDM/rZegglObGtIVyj5aiJNQhP6boWHdbq0E8qxMy4FUT04fKN8vsztseFMvdFpjinhuI/fWspXybKPIZbexVTQ7nksuuraZDbOWZLVwDmJUBKN1gyNqQKSjEFQBgAHUPHAUb0wSayf6Q2Er8gD2zrpzfg12Mu2ErWr4YJRL7Cx+uVtw6g2sI6i10P4B8nEjKFpjRaTG/ogLAjr2O+FxFxHyAu+JfJYMyOiszEz+jC1654DKjwkagy5dxgXP6rMx1rtCf270TBvRgVAS72EtpdpQYGtki5hxXufI0GzdP0z8y6RasfVBYNCsi+750E8zP//SYKQ1YZN4YAlCLym8W23vSq9aJUy4zk6eDmRdKOqUbsjYRqr3DsTfj2/iXmeVRgmdxQ0UhbcOGSjNuSx4g+Q+TbdBQhAdzAigHDlwTiX2qoniKywLUJZeApOMtktVDUd5E3nl/arT1/ZIzHuuX4W/Gy5er7G6MUD/5Lwf07pit/+Qw2F4gNnWTzIz+qvfhDOrWKE/IS/tA21jpZRm0BUj6Uj5YDZEVMJOQIftta8GXqFmK3Vcpjztt3mlAExxRg8JQu9D1c3bA=
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    node: '6'
