# Travis CI Configuration File
group: travis_latest
# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:   
#  - 5.4
#  - 5.5
#  - 5.6
#  - hhvm

# WordPress version used in first build configuration.
env:
    - WP_VERSION=master

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.
matrix:
  include:
    - php: 7.1.3
      dist: precise
      env: WP_VERSION=master
    - php: 5.6
      dist: precise
      env: WP_VERSION=3.8

# In case of timeouts and build failures you may want to prepend 'travis_retry' to the following commands:
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install -n

script:
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
