language: php
sudo: required
php:
 - '7.1'
# - '5.6'

services:
 - mysql

before_script:
 - composer update
 - composer self-update
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)


install:
#- travis_retry composer update --no-interaction --prefer-source --dev
#- travis_retry composer install --no-interaction --prefer-source --dev
- travis_retry composer update --no-interaction --prefer-source
- travis_retry composer install --no-interaction --prefer-source

notifications:
 on_success: never
 on_failure: always
