sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
env:
  global:
    # secure: EH/jxnQ5uY+RQ64BahYXh8Y6+pJ8pNpQWVqW3HDgnzuFytH+M3aB1q1fgZ/FY+B59KKE1ljAlhlNKp9tx5U2jo5lDewPCxX1jXkWH4XfnQaUWmAi//huWhYzWidZVRa01vJmffN+kwIEKwrjqHHMBzsoC5qA1zWYB1J3aFuwoVnsR4N0uegHrXTABIcKoS4m1ml131TYaMuDTawtXTUEmmNYxs7QlPvmlJveChm81i1XbGuZh5/p83HMA9ujdw6X93BoTrsDetXSSxMHSzt8XaDWsTjqwQgGYDl7zsLtcahOtnW/+vRH3dUe277E1wbsdabANcJAORA9EtLbrbTsWnqq8e2RmzVhKzUubLWetWINPZ9sKvON5CnNkhMhMgB72mtH9Ey490OMZnYI131zdp6eTB8MQ2y576ZNpMRAsW6EbUMtdXKGDqo625NmZ58LmJF28FgVPS1BFpG4j/NTne8jZbAIs2Be7trMyxQODgQOQyJZsm26Vwtw1P/I/swrZuXRKL5iprPUwi5fuEAqOn8zKQh8J6QzbfsvhjnjMZPLmcG5Jnim13557DOKnoSvmjNrP0T+4qAHRMg8fjKOTthwkElazBw3gBBI3sivJUzaS39Z39gajJjmQFyYlmg+Sf7c9ooIBiSrUsvINdn6tk/mAlV5rjsvixHfa1VubZY=
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- echo ${TRAVIS_NODE_VERSION}-${TRAVIS_TAG}
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  api_key: 70e92c02733fe70ac3f176ab3c7b5b0f2f9a4b7f
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
