sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
#- '5'
#- '4'
env:
  global:
    secure: WdzG2DMAp/3y7PTNtL3mxHq0e5PfKTPWgiw3LRqjjSK/26tBCe/lACy/1HdtXw1iQIe24J3IU7KuYVxyrXddG4TB+2DdGxjDPFM2RZE/syhEz/x5cemmzemhZH587eX+l4liSoz6kA5y811l+0p1FZPyXPkdQ/Vi9DYO4nHaVrNyhhz88Xdx4JbKNWW7mCWErp5SgCrp9J/VGXOv2bej4mBBc5i9gxFg8Y+mhdbbs8tybJeSfnVdE7V3Ocfz9Qz8OS1uDD9XpaVF38JoxUXyHOx8azkJXRvkqk+t+XnptR/nay8ddohVf6E1cu4x6mdFDS4wQ5QSIPIo5w9Pf2Oh2giSeFMtne4a60Ymkn6vRW2Ix5xP336d7CYGQOpHtS1sl7jwTjp0lSJ0OHQwx4c+T4jwWdG0r5PCrSQPQu6bxl1Fyz5vEbER037Ejr7DtaBtJvA8CcUSR4bkRrGrRQyCofQYn4idwTTpFe3aGPJ5uZh38+Pmjl6Y5ZiZZPjPs+3gCxr9ypL1WaQr9gUl8vtJvWnzgIbtmKJAnEpZA522YtLMqPs5VQzoazq83wQsERnOGnTFiJWLYIaaFC8wyBJhWsROZtac9B572isXBqXXk9Xz3+8GpY/Hx6A6Cw5qz346ZixGVy7XF5wfXMuseQg//rho/oWIEiR6Uo4iCMNMtdo=
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- echo ${TRAVIS_NODE_VERSION}-${TRAVIS_TAG}
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  api_key:
    secure: m3/Wev2JYcVtwJFAhcxhjInO2i20+uT80xethKuhxt0AeqnaEVQy3sIRU+uXsD36Yogl3BiZMCwkMKZF44IzW78o11NpXqIDM/rZegglObGtIVyj5aiJNQhP6boWHdbq0E8qxMy4FUT04fKN8vsztseFMvdFpjinhuI/fWspXybKPIZbexVTQ7nksuuraZDbOWZLVwDmJUBKN1gyNqQKSjEFQBgAHUPHAUb0wSayf6Q2Er8gD2zrpzfg12Mu2ErWr4YJRL7Cx+uVtw6g2sI6i10P4B8nEjKFpjRaTG/ogLAjr2O+FxFxHyAu+JfJYMyOiszEz+jC1654DKjwkagy5dxgXP6rMx1rtCf270TBvRgVAS72EtpdpQYGtki5hxXufI0GzdP0z8y6RasfVBYNCsi+750E8zP//SYKQ1YZN4YAlCLym8W23vSq9aJUy4zk6eDmRdKOqUbsjYRqr3DsTfj2/iXmeVRgmdxQ0UhbcOGSjNuSx4g+Q+TbdBQhAdzAigHDlwTiX2qoniKywLUJZeApOMtktVDUd5E3nl/arT1/ZIzHuuX4W/Gy5er7G6MUD/5Lwf07pit/+Qw2F4gNnWTzIz+qvfhDOrWKE/IS/tA21jpZRm0BUj6Uj5YDZEVMJOQIftta8GXqFmK3Vcpjztt3mlAExxRg8JQu9D1c3bA=
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    #tags: true
    #node: '6'
    branch: master
