#custom travis.yml
language: php
php:
  #- '5.4'
  - '7.2'
  - '7.1'
  #- hhvm # on Trusty only
  #- nightly

group: deprecated-2017Q4

before_script:
  - sudo apt-get update
 # - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
 - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 #install phpdbg dep
 - cd /usr/src/php-src/sapi
 - git clone https://github.com/krakjoe/phpdbg
 - cd ../
 - ./buildconf --force
 - ./configure --enable-phpdbg
 - make -j8
 - make install-phpdbg
 - composer update

# before_script:
#   - sudo apt-get update
#   - sudo apt-get install '^php7. *
#   - composer update
#   # enable php-fpm
#   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
#   - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
#   - sudo a2enmod rewrite actions fastcgi alias
#   - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#   - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
#   - sudo chown -R travis:travis /var/lib/apache2/fastcgi
#   - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
#   # configure apache virtual hosts
#   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
#   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
#   - sudo service apache2 restart

#before_script: composer require atoum/atoum
#script: vendor/bin/atoum
install:
  # - ./bin/ci/install_dependencies.sh
  # - php vendor/vendors.php
