# faster builds on new travis setup not using sudo
sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
#  fast_finish: true
  include:
    # test against the latest HHVM version by using trusty
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Use edge image until the next travis CI image update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
  allow_failures:
    - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer --prefer-source --dev install

script:
    - phpunit --coverage-text tests
