sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
env:
  global:
    secure: hZD0NIb1unLDZERMuCgJfEROOlTIEt6AYCQSTBlC9GE2o7Yz1DViK8vxAgEmCAByjY4wV4Nz0G4hRuQOt+S1bu1d9HtYrJu3fAlWpx/e0764A8WAknSwnEF8qvd4peiq2iBzM1tx5lEteZnVHFSmP8Bgjke2eFOV8ZaEzMaFT16iuGawfsLGoW84hH8kLzEjGN6bHosFDtr8hqV+ljZJ4eXd14qzrWxmYRGUZRIo+jHOUIK8gn/I1uoGMcQ7M1JNUfjmIB9aUtbwANbdtD1qMDd6BJzPGW+UZ/j+7pz70UaR3bMr5y+GjgXg9z9UTfQtACFqU+ZaxjLdTy0U6Pfxeg/+KraQHBPikQEyweT9pEFKfreBojxyGEKr7aFsebKo/pfz715rq/gjYocClLRjv11bgymw/bPqDmirnhvJiIMO/u6c3UZAscHRRNqYA4fN8nbBWd6Q4p1QhabfzWWm6ESFWPZzVDZYF6VN5dII8fACB2U5JEnVMDr8saSHrQOwf0Gn0Kx3zGsJ/NkBHhQM0d3sUHpgbBh+MirGZIvBmoud0FFrY8XJ6DR7KECpuEU8iWLKMn/q4jQGzL7Do7bwpBbnYap/3XKVb/Zvk3Xf1I6OHxck8djELixoN0N2XmJnV8xjhGjArKgmT8YALWuVJnSIwS4Uz6QRp6JHlPoI1d8=
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- echo ${TRAVIS_NODE_VERSION}-${TRAVIS_TAG}
- git config --local user.name "buluma"
- git config --local user.email "bulumaknight@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  api_key: 
    secure: l/6RsqAHDouhTaAsiGjvxVyReonlTQzzMTw3A34d3S3T2dwnT6oZaKfOuukGhIzxxk9S3RL1XWD4X9p0QKQTQO7+72jRsg2TY3FL1H3EbeUrT17Pgft+I03MyDGDbCuMTdhKhK+13XtitCH2Jnv40c/iKAEFCjV1/TAiU38Gc5sOq7YX7THtNpiPYnbkBlZbJzKfKn+cIVCG1NBAgolgDA1iPZIgu+qfX87S9A9dCcM7aagODIdkhLu6tiP2uLNU8IoqUi7r8oFlwdvfpxt9PxZVJhiR8yEOF8xL41vgx8kKY4xQxs/lL+zbXP8QcVCAhcPV7dQyufWMKX0jYnG1cHWIourrLNGpO0fBT4feUNt6EmRDs1mtmHd3NaHRgAj+uQs8i41dyoS9GaoQerP67LTFJDdxI5Os1l+1IcbpclIOVocx5mW9vvbRYUB3Dy4El/6reFZj85iY7c979oKyEgmKa3N7sUrLIV6VEGgJcH2cg4UlEnm/tkx3vyxCn1oJg2kmDhvoQlsthvyskfxmsvULaW2TnIw1WwPMNuIhY1yEoQe1dpo5a7/K7qqDl6o56go2s4nCRswueR6dtc92C/HcsjBfOnMxpnE3yo+sRI/7zOc2hDnwyZ/EFO8kdvnV4OhU/utkmcvTfIiVib9aJ6SJL4FmWvrnsF6IIjwcJQ8=
  # passwordx: s9KEqMOvgLGv
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
    
