sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
#- '5'
#- '4'
env:
  global:
    secure: LZtC2VpPdxom1NoFm9/GsZLM0KdcS7c5RNec4k2xRLmg8Hfo5eozVCzyP+Ia51nXwHanWz4h68qf7KIeluFz6oy5lrbO8qjBi45gB2LDodUn+BcU2g3ydZ2ji0OTYjfatgLcSTfV0oejO5r8SqvH3j1mzpbbW4WcsgZP2Bgw6I38LCrnu6peu+UgG3K2gKUvu0WSZRbJ7KZgUF8QeBslIIgTzKeffoBIWME/CxocVLHXhJ5WJpA8tETIXepDG2cKXdWszNEJ/oKfnuUWtFSL9I+dPJFVXZnw+EfApxUPNucA/go7O1KViZg0UpLRT0JBrDNjHHog93+wNZrn55ceY/63PULzQUaTzJQ2Xq+ONpLFMhYmrtte9W/rKuI1orK19aJdKBLXWDg1Y6PbgxqcfFwnqh0uBu4gjiSjni8g6Zo41o1FCHZaBLdl79Vw22susj4YFtLOmiWi3790X/pkn1hGLzPFcxoF7bqGBlAW5v6l9IHUsU9r/X2QlaQytiL3B+nyDHeYHSQM4QjTG2LHZZbHOx5ZUvPlFLdmXxe9LwAwWmbcaVGVoiByDvXgCD+HQPY/WtHtQPN06eZIWhgna62gfdsbzoFcNODWHOA797mnNXU8i6w4NS34TBX5FVASc+rz3gKLbWcIwbOU1ku1tYFkVfAUD1Ssun7zNjQMbpE=
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- Travis_version=${TRAVIS_NODE_VERSION}
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  api_key:
    secure: LZtC2VpPdxom1NoFm9/GsZLM0KdcS7c5RNec4k2xRLmg8Hfo5eozVCzyP+Ia51nXwHanWz4h68qf7KIeluFz6oy5lrbO8qjBi45gB2LDodUn+BcU2g3ydZ2ji0OTYjfatgLcSTfV0oejO5r8SqvH3j1mzpbbW4WcsgZP2Bgw6I38LCrnu6peu+UgG3K2gKUvu0WSZRbJ7KZgUF8QeBslIIgTzKeffoBIWME/CxocVLHXhJ5WJpA8tETIXepDG2cKXdWszNEJ/oKfnuUWtFSL9I+dPJFVXZnw+EfApxUPNucA/go7O1KViZg0UpLRT0JBrDNjHHog93+wNZrn55ceY/63PULzQUaTzJQ2Xq+ONpLFMhYmrtte9W/rKuI1orK19aJdKBLXWDg1Y6PbgxqcfFwnqh0uBu4gjiSjni8g6Zo41o1FCHZaBLdl79Vw22susj4YFtLOmiWi3790X/pkn1hGLzPFcxoF7bqGBlAW5v6l9IHUsU9r/X2QlaQytiL3B+nyDHeYHSQM4QjTG2LHZZbHOx5ZUvPlFLdmXxe9LwAwWmbcaVGVoiByDvXgCD+HQPY/WtHtQPN06eZIWhgna62gfdsbzoFcNODWHOA797mnNXU8i6w4NS34TBX5FVASc+rz3gKLbWcIwbOU1ku1tYFkVfAUD1Ssun7zNjQMbpE=
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    repo: buluma/buluma-wordpress
