sudo: required
dist: trusty
group: edge
language: node_js
os:
- linux
node_js:
- '6'
env:
  global: 
before_install:
- npm install -g npm
- npm --version
install:
- npm install
after_success:
- mkdir -p releases
- PACKAGE_NAME=`scripts/package-name.sh package.json`
- PACKAGE_VERSION=`scripts/package-version.sh package.json`
- RELEASE=${PACKAGE_NAME}-${PACKAGE_VERSION}
- echo ${TRAVIS_NODE_VERSION}-${TRAVIS_TAG}
- git config --local user.name "buluma"
- git config --local user.email "bulumaknight@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- COMMIT_HASH=`git log -1 --format="%h"`
- |
  if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    pushd releases;
    ln -sf ../src ${RELEASE};
    zip -r ${RELEASE}.zip ${RELEASE};
    popd;
    ls -al releases/*;
    if [[ -z "$TRAVIS_TAG" ]]; then
      mv "releases/${RELEASE}.zip" "releases/${RELEASE}-${COMMIT_HASH}.zip";
      npm run github-release -- delete \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        "*.zip";
      npm run github-release -- upload \
        --owner=buluma \
        --repo=buluma-wordpress \
        --tag="latest" \
        --name="${TRAVIS_BRANCH}" \
        --body="${COMMIT_LOG}" \
        "releases/${RELEASE}-${COMMIT_HASH}.zip";
    fi
  fi
before_deploy:
- echo "Deploying to GitHub releases"
- ls -al releases
deploy:
  provider: releases
  user: buluma
  password: UYWOSVaAae1xe73bIdf+8a6QQzui9/S2EhAdm7J1B+ZJx3xI2yLpOT0AtejJFktcOCtzWAQ4mYwGyKjAt4WSA5ntlHOBMJFFKOppg2edUPhJ5VtnbGs3c6M3J/IfFEOoQRVREU3oOQqE0Pab95ZpFQ5HEDREhNVv/T8XVtbxckk3hr1IkIbDBH2zCxHpbOFBdl0rSv4V5Hs2HiMfAS633cfZGpjjAIfQ9w8HVUdlTN6O2oOXdf5Qbb6JU3+fDiEK2kW5zCcs9SCdl/mahMVZDoNPvoV0kgooH9hYQGEFFsByW7Ky8t0v62GMeP+R28jF0n4sMrc5EjYjCww5qxgyNkW9u4lIkHHY0ZhFvtMR+6BCEL3sAF8FhDWFDz9qYyT4i07/fhhj4MIZ3YW+XIUoM6c7QNCDBGXU3DlTSjhcRfixMvfm1nC8xO475NGqyl1Pi8Gk53e5c72M9qDgDSQz4zx8eX+bbqYUYVc+8c8ZNe55Qytn9xw/1oV1AbB8GNOduDqZmK9gUVRqPvxltaVBYXXI5CCOG5jsgShXKeuHhZ68rJ9QoU3myV1RouboupzZ6GKlJJjtWSpcqvuc4wrOfNyAmU10efmvDn5T2/XZxc5jBRugBSamPtq7RoZOm9t6MkmfCDD/kuAXn0u+90wPVvY38vCe1dA91CKFXooWHRw=
  file_glob: true
  file:
  - releases/*.*
  overwrite: true
  skip_cleanup: true
  on:
    tags: false
    node: '6'
notifications:
  email: ops@buluma.me.ke
