# faster builds on new travis setup not using sudo
sudo: false
language: php

php:
#  - 5.4
#  - 5.5
#  - 5.6
  - 7.0
  - 7.0.8

matrix:
#  fast_finish: true
  include:
    # test against the latest HHVM version by using trusty
    - php: 7.2
      sudo: true
      dist: precise
      group: edge # Use edge image until the next travis CI image update
      addons:
        apt:
          packages:
            - mysql-server
            - mysql-client-core
            - mysql-client
      services:
        - mysql

before_script:
    - travis_retry composer update 
 #   - travis_retry composer --prefer-source --dev install
 #   - ls

script:
    #- ls -a /home/travis/build/buluma/buluma-wordpress/vendor/codacy/coverage
    - cd /home/travis/build/buluma/buluma-wordpress/
    - ls -a /home/travis/build/buluma/buluma-wordpress/vendor/
    - ls -a /home/travis/build/buluma/buluma-wordpress/tests/
    #- vendor/bin/phpunit -c .
    #- vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox test
    - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
